<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Metatron: A Distributed Computing Language and Virtual Machine
  ~ Copyright (C) 2025- PhaseShift Studio, LLC
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>studio.phaseshift.metatron</groupId>
    <artifactId>metatron</artifactId>
    <version>0.1-SNAPSHOT</version>
    <name>metatron</name>
    <url>http://metatron.phaseshift.studio</url>
    <packaging>jar</packaging>
    <contributors>
        <contributor>
            <name>Marko A. Rodriguez</name>
            <email>marko@markorodriguez.com</email>
            <organization>PhaseShift Studio</organization>
        </contributor>
    </contributors>
    <licenses>
        <license>
            <name>AGPL License</name>
            <url>https://raw.githubusercontent.com/phaseshift-studio/metatron/refs/heads/main/LICENSE</url>
        </license>
    </licenses>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>22</maven.compiler.source>
        <maven.compiler.target>22</maven.compiler.target>
        <maven.compiler.release>22</maven.compiler.release>
        <java.version>22</java.version>
        <skipTests>false</skipTests>
        <!-- DEPENDENCY VERSIONS -->
        <java-websocket.version>1.6.0</java-websocket.version>
        <sqlite.version>3.51.1.0</sqlite.version>
        <langchain4j.version>1.10.0</langchain4j.version>
        <langgraph4j.version>1.8.0</langgraph4j.version>
        <junit.version>6.0.2</junit.version>
        <tinkerpop.version>3.8.0</tinkerpop.version>
        <jlama.version>0.8.4</jlama.version>
        <gson.version>2.13.2</gson.version>
        <petitparser.version>2.4.0</petitparser.version>
        <jline.version>3.30.6</jline.version>
        <logback.version>1.5.27</logback.version>
        <slf4j.version>2.0.17</slf4j.version>
        <hive.version>1.3.12</hive.version>
        <jakarta.version>2.2.0</jakarta.version>
        <jsoup.version>1.22.1</jsoup.version>
        <asciidoctor.version>3.2.0</asciidoctor.version>
        <exp4j.version>0.4.8</exp4j.version>
        <llama4j.version>0.1.1</llama4j.version>
        <ollama4j.version>1.1.6</ollama4j.version>
        <guice.version>7.0.0</guice.version>
        <moquette.version>0.18.0</moquette.version>
        <dockerfile-maven.version>1.4.13</dockerfile-maven.version>
        <commonmark.version>0.27.1</commonmark.version>
        <jserialcomm.version>2.11.4</jserialcomm.version>

        <!-- LOGBACK PROPERTIES -->
    </properties>
    <dependencyManagement>
        <dependencies>
            <!-- LANGGRAPH -->
            <dependency>
                <groupId>org.bsc.langgraph4j</groupId>
                <artifactId>langgraph4j-bom</artifactId>
                <version>${langgraph4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- TINKERPOP -->
            <dependency>
                <groupId>org.apache.tinkerpop</groupId>
                <artifactId>tinkerpop</artifactId>
                <version>${tinkerpop.version}</version>
                <type>pom</type>
            </dependency>
            <!-- TESTING -->
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.github.tjake</groupId>
                <artifactId>jlama-native</artifactId>
                <!-- supports linux-x86_64, macos-x86_64/aarch_64, windows-x86_64
                     Use https://github.com/trustin/os-maven-plugin to detect os and arch -->
                <classifier>${os.detected.name}-${os.detected.arch}</classifier>
                <version>${jlama.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <!-- SERIAL PORTS -->
        <dependency>
            <groupId>com.fazecast</groupId>
            <artifactId>jSerialComm</artifactId>
            <version>${jserialcomm.version}</version>
        </dependency>
        <!-- SQLITE -->
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>${sqlite.version}</version>
        </dependency>
        <!-- LANGCHAIN -->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
            <version>${langchain4j.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-ollama</artifactId>
            <version>${langchain4j.version}</version>
        </dependency>
        <!-- LANGGRAPH -->
        <dependency>
            <groupId>org.bsc.langgraph4j</groupId>
            <artifactId>langgraph4j-core</artifactId>
        </dependency>
        <!-- TINKERPOP -->
        <dependency>
            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>gremlin-core</artifactId>
            <version>${tinkerpop.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>tinkergraph-gremlin</artifactId>
            <version>${tinkerpop.version}</version>
        </dependency>
        <!-- JLAMA -->
        <dependency>
            <groupId>com.github.tjake</groupId>
            <artifactId>jlama-core</artifactId>
            <version>${jlama.version}</version>
        </dependency>
        <dependency>
            <groupId>com.llama4j</groupId>
            <artifactId>gguf</artifactId>
            <version>${llama4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.ollama4j</groupId>
            <artifactId>ollama4j</artifactId>
            <version>${ollama4j.version}</version>
        </dependency>
        <!-- NETWORKING -->
        <dependency>
            <groupId>jakarta.websocket</groupId>
            <artifactId>jakarta.websocket-api</artifactId>
            <version>${jakarta.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.java-websocket</groupId>
            <artifactId>Java-WebSocket</artifactId>
            <version>${java-websocket.version}</version>
        </dependency>
        <!-- PARSERS -->
        <dependency>
            <groupId>org.commonmark</groupId>
            <artifactId>commonmark</artifactId>
            <version>${commonmark.version}</version>
        </dependency>
        <dependency>
            <groupId>net.objecthunter</groupId>
            <artifactId>exp4j</artifactId>
            <version>${exp4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${gson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>${jsoup.version}</version>
        </dependency>
        <!-- CONSOLE -->
        <dependency>
            <groupId>org.jline</groupId>
            <artifactId>jline</artifactId>
            <version>${jline.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jline</groupId>
            <artifactId>jline-terminal-jansi</artifactId>
            <version>${jline.version}</version>
        </dependency>
        <!-- LOGGING -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <!-- PARSING -->
        <dependency>
            <groupId>com.github.petitparser</groupId>
            <artifactId>petitparser-core</artifactId>
            <version>${petitparser.version}</version>
        </dependency>
        <!-- CONNECTORS -->
        <dependency>
            <groupId>com.hivemq</groupId>
            <artifactId>hivemq-mqtt-client</artifactId>
            <version>${hive.version}</version>
        </dependency>
        <!-- TESTING -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>${guice.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.tinkerpop</groupId>
            <artifactId>gremlin-test</artifactId>
            <version>${tinkerpop.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.moquette-io.moquette</groupId>
            <artifactId>moquette-broker</artifactId>
            <version>${moquette.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>sonatype-oss-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <targetPath>${project.build.directory}</targetPath>
                <includes>
                    <include>logback.xml</include>
                    <include>ansi_headers.txt</include>
                </includes>
            </resource>
        </resources>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.7.1</version>
            </extension>
        </extensions>
        <!--
        ####################################################################################################
        ####################################################################################################
        ###### PLUGINS #####################################################################################
        ####################################################################################################
        -->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.7.1</version>
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <goals>
                            <goal>detect</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>run-python-script</id>
                        <phase>site</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>python</executable>
                            <arguments>
                                <argument>docs/python/docs-code-parser.py</argument>
                                <argument>--verbose</argument>
                                <argument>-o</argument>
                                <argument>${project.build.directory}/temp</argument>
                                <argument>${project.basedir}/docs</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>studio.phaseshift.metatron.BootLoader</mainClass>
                    <addResourcesToClasspath>true</addResourcesToClasspath>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>studio.phaseshift.metatron.BootLoader</mainClass>
                            <classpathPrefix>lib/</classpathPrefix>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/assembly.xml</descriptor>
                            </descriptors>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                            <archive>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <classpathPrefix>lib/</classpathPrefix>
                                    <mainClass>studio.phaseshift.metatron.BootLoader</mainClass>
                                </manifest>
                                <manifestEntries>
                                    <Build-Timestamp>${maven.build.timestamp}</Build-Timestamp>
                                    <Project-Version>${project.version}</Project-Version>
                                    <Java-Version>${java.version}</Java-Version>
                                    <Enable-Native-Access>ALL-UNNAMED</Enable-Native-Access>
                                </manifestEntries>
                            </archive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>pre-site</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <outputDirectory>${project.build.directory}/temp</outputDirectory>
                    <resources>
                        <resource>
                            <directory>${project.basedir}/docs</directory>
                            <includes>
                                <include>css/**</include>
                                <include>javascript/**</include>
                                <include>highlight/**</include>
                                <include>images/**</include>
                            </includes>
                            <filtering>true</filtering>
                        </resource>
                    </resources>
                </configuration>
            </plugin>
            <!--<plugin>
                <groupId>uk.bot-by.maven-plugin</groupId>
                <artifactId>ijhttp-maven-plugin</artifactId>
                <version>1.0.1</version>
                <executions>
                    <execution>
                        <configuration>
                            <environmentFile>${project.basedir}/src/test/resources/ijhttp/http-client.env.json
                            </environmentFile>
                            <environmentName>dev</environmentName>
                            <files>
                                <file>${project.basedir}/src/test/resources/ijhttp/mtron-server.http</file>
                            </files>
                            <logLevel>HEADERS</logLevel>
                            <report>true</report>
                            <workingDirectory>target</workingDirectory>
                        </configuration>
                        <phase>test</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <id>simple-run-with-report</id>
                    </execution>
                </executions>
            </plugin>-->
            <plugin>
                <groupId>com.spotify</groupId>
                <artifactId>dockerfile-maven-plugin</artifactId>
                <version>${dockerfile-maven.version}</version>
                <executions>
                    <execution>
                        <id>default</id>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <skip>${skipTests}</skip>
                    <repository>${project.artifactId}</repository>
                    <tag>${project.version}</tag>
                    <contextDirectory>${project.basedir}</contextDirectory>
                    <dockerfile>dist/docker/Dockerfile</dockerfile>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>${asciidoctor.version}</version>
                <configuration>
                    <sourceDirectory>${project.build.directory}/temp</sourceDirectory>
                    <sourceDocumentName>index.adoc</sourceDocumentName>
                    <outputDirectory>${project.build.directory}/docs</outputDirectory>
                    <resources>
                        <resource>
                            <directory>${project.build.directory}/temp</directory>
                            <targetPath>${project.build.directory}/docs</targetPath>
                            <excludes>
                                <exclude>**/.txt</exclude>
                                <exclude>**/.py</exclude>
                            </excludes>
                        </resource>
                    </resources>
                </configuration>
                <executions>
                    <execution>
                        <id>convert-to-html</id>
                        <phase>site</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
                <version>1.14</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                            <verbose>true</verbose>
                            <controlDir>${project.basedir}/dist/deb/control</controlDir>
                            <dataSet>
                                <!--<destFile>${project.build.directory}/${project.build.finalName}-linux.deb</destFile>-->
                                <data>
                                    <src>${project.build.directory}/${project.build.finalName}-jar-with-dependencies.jar</src>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/usr/share/java</prefix>
                                    </mapper>
                                </data>
                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <!--
        ####################################################################################################
        ####################################################################################################
        ###### PLUGIN MANAGEMENT ###########################################################################
        ####################################################################################################
        -->
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>3.6.3</version>
                </plugin>
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.4.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.15.0</version>
                    <configuration>
                        <source>${maven.compiler.release}</source>
                        <target>${maven.compiler.release}</target>
                        <compilerArgs>
                            <arg>--add-modules</arg>
                            <arg>jdk.incubator.vector</arg>
                            <arg>-XDsun-misc-unsafe-memory-access=allow</arg>
                            <arg>-XDenable-native-access=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.io=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.nio=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/sun.nio.cs=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.lang=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.lang.invoke=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.lang.reflect=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.util=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.util.concurrent=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED</arg>
                            <arg>--add-opens=java.base/java.net=ALL-UNNAMED</arg>
                            <!--<arg>-XDlogback.configurationFile=file:./conf/logback.xml</arg>-->
                        </compilerArgs>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.4</version>
                    <configuration>
                        <argLine>
                            --sun-misc-unsafe-memory-access=allow
                            --enable-native-access=ALL-UNNAMED
                            --add-modules jdk.incubator.vector
                            --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED
                            --add-opens java.base/java.io=ALL-UNNAMED
                            --add-opens java.base/java.nio=ALL-UNNAMED
                            --add-opens java.base/sun.nio.cs=ALL-UNNAMED
                            --add-opens java.base/java.lang=ALL-UNNAMED
                            --add-opens java.base/java.lang.invoke=ALL-UNNAMED
                            --add-opens java.base/java.lang.reflect=ALL-UNNAMED
                            --add-opens java.base/java.util=ALL-UNNAMED
                            --add-opens java.base/java.util.concurrent=ALL-UNNAMED
                            --add-opens java.base/java.net=ALL-UNNAMED
                            --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED
                        </argLine>
                        <systemPropertyVariables>
                            <logback.configurationFile>
                                ${basedir}/src/test/resources/logback-testing.xml
                            </logback.configurationFile>
                        </systemPropertyVariables>

                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>3.1.4</version>
                    <configuration>
                        <allowIncompleteProjects>true</allowIncompleteProjects>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.1.4</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.21.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>3.8.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>3.9.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <configuration>
                        <classifier>${os.detected.classifier}</classifier>
                    </configuration>
                    <version>3.5.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
