[discrete]
== Math Instruction Set

The `/m/math` instruction set offers a collection of constants, types, and instructions intended for the representation and manipulation of numbers.

[discrete]
=== Units of Measurement

The subspace of __units of measurement__ offer sets of types that denote different scales of a particular physical metric.
In particular, there are types for representing and converting between units of time, units of size, units of currency, units of distance, etc.
A brief, example driven overview of these subspaces is provided below.

[discrete]
==== Time

The `/m/math/time` branch of the math instruction set provides the following types:

[cols="4a,8a",separator=🧱,role="table-bordered small center"]
|===
🧱
[mtron]
----
millis::T
second::T
minute::T
hour::T
----

🧱

[mtron]
----
millis::1000.0.as(second::T)
hour::1.5.as(minute::T)
minute::60.0.as(hour::T)
minute::1.0.gt(second::61.0)
second::1.0.lt(millis::2000.0)
----
|===

[discrete]
==== Data Size

[cols="4a,8a",separator=🧱,role="table-bordered small center"]
|===
🧱
[mtron]
----
bB::T
kB::T
mB::T
gB::T
tB::T
pB::T
----

🧱

[mtron]
----
bB::1024.0.as(kB::T)
kB::1.5.as(mB::T)
mB::1000.0.as(tB::T)
mB::1.0.gt(bB::600.0)
gB::1.0.lt(kB::12000000.0)
----
|===

[discrete]
==== DateTime

The `/m/math/datetime` type is a `uri::T` refinement representing a calendar datetime with structure `//yyyy.MM:dd/HH/mm/ss/SSS?tz=±HHmm`.

[cols="4a,8a",separator=🧱,role="table-bordered small center"]
|===
🧱
[mtron]
----
datetime::T
----

🧱

[mtron]
----
datetime_now()                                                                       [-- <1> --]
<//2024.12:25/09/00/00/000?tz=-0500>?datetime::T                                     [-- <2> --]
datetime::<//2024.12:25/09/00/00/000?tz=-0500>>>year                                 [-- <3> --]
datetime::<//2024.12:25/09/00/00/000?tz=-0500>>>month                                [-- <4> --]
datetime::<//2024.12:25/09/00/00/000?tz=-0500>>>day                                  [-- <5> --]
datetime::<//2024.12:25/09/00/00/000?tz=-0500>>>{hour,minute,second,millis}          [-- <6> --]
<//2024.12:25/09/00/00/000?tz=-0500>>>host                                           [-- <7> --]
<//2024.12:25/09/00/00/000?tz=-0500>>>port                                           [-- <8> --]
<//2024.12:25/09/00/00/000?tz=-0500>>>path>>0                                        [-- <9> --]
<//2024.12:25/09/00/00/000?tz=-0500>==[port=>+1]>>port                               [-- <10> --]
<//2024.12:25/09/00/00/000?tz=-0500>=?=[port=>25]                                    [-- <11> --]
<//2024.12:25/09/00/00/000?tz=-0500>.as(rec::T)>>=[q=>[tz=>'+0000']].as(datetime::T) [-- <12> --]
'2026-08-01T23:37:33-06:00'.as(datetime::T)>>year                                    [-- <13> --]
'2026-08-01 23:37:33 -0600 MDT'.as(datetime::T)>>tz                                  [-- <14> --]
'2024-12-25T09:00:00Z'.as(datetime::T)>>{year,month,day}                             [-- <15> --]
----
<1> construct a `datetime::T` representing the current date and time.
<2> type-check: validate that the `uri::T` satisfies the `datetime::T` structure (returns the value, or `noobj` if it doesn't).
<3> project the `year` component of the `datetime::T` value.
<4> project the `month` component of the `datetime::T` value.
<5> project the `day` component of the `datetime::T` value.
<6> project the `hour`, `minute`, `second`, and `millis` components as a set.
<7> `datetime::T` refines `uri::T` and so the standard `uri::T` projections can be applied.
<8> project the `port` (day of month) component of the `datetime::T` value.
<9> project a path component of the `datetime::T` value (hour at index `0`).
<10> `select` mutation: extract `datetime::T` `port` (day) and add 1.
<11> `where` filter: keep the value only when `port` (day) is `25`.
<12> `record` round-trip: convert to `rec::T`, update the `tz` query field, and cast back to `datetime::T`.
<13> parse an https://en.wikipedia.org/wiki/ISO_8601[ISO-8601] string with timezone offset into a `datetime::T`.
<14> parse a Docker-format timestamp (space-separated, timezone name) into a `datetime::T`.
<15> parse a UTC / Zulu timestamp into a `datetime::T`.
|===