[discrete]
== Uniform Resource Identifiers

[source,mtron]
----
file://domain.local:22/usr/data/abc{*}?sub
  │    └──────────┘ │  └──────────┘ │  └────⮞ q(uery)
  │          │      │        │      └───────⮞ c(oefficient)   
  │          │      │        └──────────────⮞ path
  │          │      └───────────────────────⮞ port
  │          └──────────────────────────────⮞ host
  └─────────────────────────────────────────⮞ scheme
----

[cols="7a,5a",separator=🧱,role=noborder]
|===
🧱

metatron was designed to support the creation and manipulation of _abstract data types_ in a manner that affords the user a concise, fluid means of maneuvering through a heterogeneous set of data structures, where each is embedded within and across any number of spaces, while being respectfully agnostic to each space's espoused perspective on the data maintained therein: e.g., key/value, document, relational, vector, graph, file system, and the various peculiarities between.

metatron's URI addressing scheme makes it possible to encode arbitrary data types into a metatron-specific construct called "space". A space is where URI/obj pairs are written to and read from. Coupling occurs when a URI references an obj. The most basic form of read/write is to dereference/reference using the instructions `from` and `to` with signatures

[source,mtron]
----
from?B{*}<=A{?}(?uri::T)
to?A{?}<=A{?}(?uri::T)
----

and example usages

[source,mtron]
----
1.to(a) [-- write 1 to a  --]
from(a) [-- read 1 from a --]
----

along with their respective sugar forms:

[source,mtron]
----
a -> 1  [-- write 1 to a --]
*a      [-- read 1 from a --]
----

From `to` and `from` more complex read/write patterns are realized such `select` and `update` (discussed elsewhere in the Tractatus).


🧱
[source,mtron]
----
               ┌─────── a/b       
 ┌─────────────┼────────────── b       
 │     ┌───────┼─────────── a/b/c      
 │     │   ┌───┼─── http://localhost:8080                
 │   ┌─▼┐  │  ┌▼┐                           
┌▼─┐ │  │  │  └─┘                           
│  │ └──┘┌─▼┐    ┌──┐                       
└──┘  ┌─┐└──┘ ┌─┐│  ◄──────── a.local         
 ┌────►─┘     └▲┘└──┘                       
 │ ┌─┐ ┌─◄┐┌──┐│    ┌◄─────── xyz        
 │ └▲┘ └─┘││  ││    └┘                      
 │  │ ┌──┐│└─▲┘└─────── mtron:ab            
 │  │ │  ││  └───────────── z        
 │  │ └─▲┘└────────────────── /a/b        
 │  │   └────────────── xx:host.com/abc        
 │  └───────────────────────── yy       
 └────────────────────── xx     
----

|===

Any obj can be referenced by a URI. From simple **mono** objs such as `bool`, `int`, etc. to complex nested **poly** objs such as `rec`, `lst`, etc. Poly objs provide another layer of addressing in that once a poly obj has a URI reference, the internal objs that make up the poly inherit that reference and extend it with any internal references necessary to find the objs within the poly.

[cols="8a,6a",separator=🧱]
|===
🧱
[source,mtron]
----
a/b/c -> [x,[y=>[z=>2]]]
         ▲▲ ▲   ▲   ▲  
         ││ │   │   └────── a/b/c/y/z     <5>
         ││ │   └────────── a/b/c/1/y     <4>
         ││ └────────────── a/b/c/1       <3>
         │└──────────────── a/b/c/0       <2>
         └───────────────── a/b/c         <1>
----

[mtron]
----
a/b/c -> [x,[y=>[z=>2]]]   
*a/b/c                     [-- <1> --]
*a/b/c/0                   [-- <2> --]
*a/b/c/1                   [-- <3> --]
*a/b/c/1/y                 [-- <4> --]
*a/b/c/1/y/z               [-- <5> --]
----

🧱
<1> the uri `a/b/c` references a `lst` poly.
<2> the uri `a/b/c/0` references an internal `uri` mono.
<3> the uri `a/b/c/1` references an internal `rec` poly.
<4> the uri `a/b/c/1/y` references another internal `rec` poly.
<5> the uri `a/b/c/1/y/z` references an doubly internal `int` mono.
|===


[discrete]
=== Spatial Embeddings

[discrete]
==== The Poly Read/Write SubRing

When a poly containing nested poly structures is written to space an ambiguity emerges. A example will elucidate this point. Assume the two ways in which to encode "the same" data in space.

[cols="8a,8a"]
|===
|

[cols="5a,5a",option="header"]
!===
^!
**form A**
^!
**form B**
!
[source,mtron]
----
[a=>[b=>1,c=>2]] 
----
!
[source,mtron]
----
{[a=>[b=>1]],
 [a=>[c=>2]]}
----
!
[source,mtron]
----
  ┌──b──⮞1
a─┤
  └──c──⮞2
----
!
[source,mtron]
----
a──b──⮞1

a──c──⮞2  
----
!===
<1> the uri ring defines multiplcation as "extension", where latexmath:[x \cdot y] is `x/y`.
<2> the uri ring defines addition as "branching", where latexmath:[x + y] is `{x,y}`. 

The characteristic marks of latexmath:[\ast] are `.`,`\=>`. +
The characteristic marks of latexmath:[+] are `,`, `-<`/`>-`.
|
The two examples represent the equivalent data because there exists a bijection that maps **A** to **B** and **B** to **A**. In other words, they are isomorphic structures within the category of the obj ring. The form **A** is captured by the equation:

\[
a \cdot (b + c) = \{1,2\}
\]

Form **B** has the equation:

\[
(a \cdot b) + (a \cdot c) = \{1,2\}
\]

Thus, due to the ring axiom that states multiplication distributes over addition, the two equations, while typographically different, are, in fact, algebraically equivalent.

\[
\begin{align}
a \cdot (b + c)  &= (a \cdot b) + (a \cdot c)         \\
a (b + c)        &= ab + ac \\
\end{align}
\]

|===

If the implication of these equalities is not readily apparent, then understand the following. The multiplicative union of uris to an obj is a **dependent relationship**. There exists a colocational requirement that `a` couples `b` and `c` into a single structure.

[source,mtron]
----
  ┌──b──⮞1
a─┤
  └──c──⮞2
----

On the other hand, the additive union of the uris is an **independent relationship**. There are two representations of `a` and thus, `a/b \=> 1` is distinct, requiring no colocation with `a/c \=> 2`. This means that `a/b` can be stored in a document database in Japan and `a/c` an be stored in `.txt` file on some file system in Ohio and when resolved, the same `{1,2}` result is returned upon query (albeit with different space/time characteristics compared to the multiplicative, colocated representation of the data).

[source,mtron]
----
a──b──⮞1

a──c──⮞2  
----

[mtron]
----
x0 -> [a=>[b=>1,c=>2]]
x1 -> {[a=>[b=>1]],[a=>[c=>2]]}
----

[mtron]
----
[x0,x1]>-.-<[*(* /a/b)]>-
[x0,x1]>-.-<[*(* /a/c)]>-
[x0,x1]>-.-<[*(* /a/+)]>-
[x0,x1]>-.-<[*(* /+/+)]>-
[x0,x1]>-.-<[*(* /+/b)]>-
[x0,x1]>-.-<[*(* /+/c)]>-
----

[discrete]
===== Left/Right Factors

Factorization can happen to the left and to the right. Assume, for the sake of an example, that the additive branches of the running example thus far both end with a `d` entry. If so, then the following equalities hold.

[source,mtron]
----
a──b──d──⮞1           ┌──b──d──⮞1          ┌──b──┐
                =   a─┤              =   a─┤      ├─d──⮞{1,2}
a──c──d──⮞2           └──c──d──⮞2          └──c──┘
----

The equalities below reiterate what is stated diagrammatically above.

\[
\begin{align}
\;         & (a \cdot b \cdot d) & + \;\; & (a \cdot c \cdot d) &            &=& \{1,2\} \\
a \cdot \; & ( (b \cdot d)       & + \;\; & (c \cdot d) )       &            &=& \{1,2\} \\
a \cdot \; & ( b                 & + \;\; & c )                 &  \cdot d   &=& \{1,2\}
\end{align}
\]

[mtron]
----
x0 -> [a=>[b=>[d=>1],c=>[d=>2]]]
x1 -> {[a=>[b=>[d=>1]]],[a=>[c=>[d=>2]]]}
----

[mtron]
----
[x0,x1]>-.-<[*(* /a/b/d)]
[x0,x1]>-.-<[*(* /a/b/+)]
[x0,x1]>-.-<[*(* /a/+/+)]
[x0,x1]>-.-<[*(* /+/+/+)]
[x0,x1]>-.-<[*(* /+/+/d)]
[x0,x1]>-.-<[*(* /+/c/d)]
[x0,x1]>-.-<[*(* /+/c/+)]
[x0,x1]>-.-<[*(* /a/+/d)]
----

A subsequent, practical entailment states that a ring-based dataset can be transformed from a **concatenative/multiplicative** form to a **union/additive** form so as to maintain one subset of the data in a specialized space optimized for the demands of its production requirements and the other subset in another space specialized accordingly to its requirements. For example, some data should be "hot in cache" in order to satisfy demand, while some other data should be "iced in an archive" when the production usage doesn't require a rapid response time and production costs can be reduced with cheaper disk storage. With metatron, expressing such partitions while also ensuring said partitions resolve correctly is built into the fundamental mathematics/algorithm of the system -- **the ring algebra for structural composition**.  

[discrete]
==== Isomorphic != Identical

A _matrix_ is an latexmath:[n \times m] data structure composed of latexmath:[n] vectors/row, each with latexmath:[m] elements/columns. A relational database _table_ is an example of a matrix, where the entries typically span numeric and non-numeric data types. Three general approaches to embedding a matrix or table into a space are presented below, where each makes different space/time tradeoffs, while remaining isomorphic with respect to the structural ring algebra.

[cols="5,5,5",frame=none,subs="+macros",separator=🧱,grid=cols, role="center"]
|===

^a🧱

[.big]
[source,mtron]
----
 \    |   |    /
 [■] [■] [■] [■]

-[■] [■] [■] [■]-

 [■] [■] [■] [■]
 /    |   |    \

----

^a🧱

[.big]
[source,mtron]
----
​
[■]-[■]-[■]-[■]

[■]-[■]-[■]-[■]

[■]-[■]-[■]-[■]
​
----

^a🧱

[.big]
[source,mtron]
----
​
[■]-[■]-[■]-[■]
 |   |   |   |
[■]-[■]-[■]-[■]
 |   |   |   |
[■]-[■]-[■]-[■]
​
----

a🧱

[mtron]
----
m/0/0 -> 0
m/0/1 -> 1
m/0/2 -> 2
m/0/3 -> 3
m/1/0 -> 4
m/1/1 -> 5
m/1/2 -> 6
m/1/3 -> 7
m/2/0 -> 8
m/2/1 -> 9
m/2/2 -> 10
m/2/3 -> 11
*m/0/0       [-- <1> --]
*m/0/+       [-- <2> --]
*m/+/0       [-- <3> --]
----

a🧱

[mtron]
----
m/0 -> [0,1,2,3]
m/1 -> [4,5,6,7]
m/2 -> [8,9,10,11]

*m/0/0       [-- <1> --]
*m/0/+       [-- <2> --]
*m/+/0       [-- <3> --]
----

a🧱

[mtron]
----
m -> [[0,1,2,3],  /
      [4,5,6,7],  /
      [8,9,10,11]]

*m/0/0       [-- <1> --]
*m/0/+       [-- <2> --]
*m/+/0       [-- <3> --]
----

|===

<1> Retrieve the first element of matrix `m`.
<2> Retrieve the first row of matrix `m`.
<3> Retrieve the first column of matrix `m`.

The above example demonstrates the power of structural embeddings.
The platonic matrix latexmath:[m] was embedded in a space using 3 different representations: _entry-wise_, _row-wise_, and _row-column wise_.
Next, each embedding was read: an _element read_, a _row read_ and a _column read_.
The expression used to read from each of the three embeddings is the same (typographically verbatim) and so is the result (algebraically isomorphic).
This is possible because a structure resolves up the fURI path hierarchy until it finds a match.
Once found, it then traverses within the match to resolve the remaining path segments.

.Amortized Costs in Terms of Time
[%header,width=50%,cols="l1,c1,c1,c1",role="small center"]
|===
| [.red]#embedding#              | [.red]#single-element#| [.red]#row-access#  | [.red]#column-access#
| [.red]#entry#          | \[O(1)\]       | \[O(n)\]    | \[O(m)\]
| [.red]#row#            | \[O(m)\]       | \[O(1)\]    | \[O(m)\]
| [.red]#row_column#     | \[O(1)\]       | \[O(1)\]    | \[O(1)\]
|===

The different embeddings also have different space costs, where space is defined as the amount of data accessed (i.e. retrieved from the structure) in order to satisfy the resolution of the respective fURI.

.Amortized Costs in Terms of Space
[.center]
[%header,width=50%,cols="l1,c1,c1,c1",role="small center"]
|===
| [.red]#embedding#              | [.red]#single-element# | [.red]#row-access#    | [.red]#column-access#
| [.red]#entry#          | \[O(1)\]       | \[O(n)\]      | \[O(m)\]
| [.red]#row#            | \[O(n)\]       | \[O(n)\]      | \[O(n+m)\]
| [.red]#row_column#     | \[O(n+m)\]     | \[O(n+m)\]    | \[O(n+m)\]
|===

[discrete]
=== The Algebraic Structure of Data

The examples thus far using algebra to construct and deconstruct data structures have been relatively basic. It's important to note that such equalities are recursive, and to demonstrate the point, a more complicated factorization will be presetented.

In mathematics, addition is denoted with a latexmath:[+] as in latexmath:[a + b]. In code, addition represented with a `,`. A `,` separates two independent `objs` as in `[a,b]`. For multiplication, mathematical notation uses latexmath:[a \cdot b] or latexmath:[a \ast b] or simply character incidence as in latexmath:[ab]. In code, `.` denotes multiplication. For instance, `a.b`. Given this rule, the following metatron `rec`

[mtron]
----
x0 -> [a=>[b=>[c=>1,d=>2],          /
           e=>[c=>3,d=>4,f=>5]],    /
       g=>[b=>[c=>6]]]
----

can be systematically and unambiguously transformed into the equation:

\[
\begin{align}
    a(b(c \cdot 1) + (d \cdot 2)) + (e( (c \cdot 3)  + (d \cdot 4) +  (f \cdot 5) )) +  (g(b(c \cdot 6))) \\
(a+e+g)(b(c\cdot 1) + b(c\cdot 3) + b(c \cdot 6)) + (a+e)(d\cdot 2 + d \cdot 4) \\
(a+e+g)(b(c(1+3))) + (a+e)(d(2 + 4))
\end{align}
\]

Common left side variables amongst summed components can be factored to the left. Likewise, right side variable can be factored to the right. From the inverse of distributivity, the `rec` can be written:

[mtron]
----
x1 -> [a/b => [c=>1,d=>2], /
       a/e/c => 3,         /
       a/e/d => 4,         /
       a/e/f => 5,         /
       g/b => [c=>6]]
x2 -> [a/b/c => 1,         /
       a/b/d => 2,         /
       a/e/c => 3,         /
       a/e/d => 4,         /
       a/e/f => 5,         /
       g/b/c => 6]       
----

[mtron]
----
[x0,x1,x2]>-.-<[*(* a/b/c)] 
[x0,x1,x2]>-.-<[*(* a/b/+)]
[x0,x1,x2]>-.-<[*(* a/+/+)]
[x0,x1,x2]>-.-<[*(* +/b/+)]
[x0,x1,x2]>-.-<[*(* +/b/c)]
[x0,x1,x2]>-.-<[*(* a/+/c)]
[x0,x1,x2]>-.-<[*(* +/+/c)]
[x0,x1,x2]>-.-<[*(* g/+/+)]
----