[discrete]
== Web Technologies

[%collapsible]
.web technologies setup
====
[mtron]
----
[NO_OUTPUT] import(/m/web)
[NO_OUTPUT] import(/m/llm)
catalog::[host         => <http://localhost:1234/v1>, /
          pattern      => <lmstudio:#>,               /
          name         => <openai>,                   /
          route        => [<lmstudio:>=><>]]@/sys/space/lmstudio
----
====

The `/m/web` instruction set enables a wide range of capabilities centered around `http`-based systems and websocket-based systems. Correspondingly, there exists `httpspace` and `wsspace` that manage respective network i/o connections. Along with these spaces are various serializers that provide the mtron encoding of common web document standards such as html, xml, json, markdown, and the like. 

[discrete]
=== HTTP Space

The `httpspace::T` is a space capable of spawning and managing `http` connection handlers both as servers and as clients. The pattern of an `httpspace` dictates the breadth of resources accessible. When `http://#` is the pattern, the world wide web becomes a source of metatron objs.

[mtron]
----
httpspace::[                                                   /
 host     => http://localhost:8777,                            /
 pattern  => http://#,                                         /
 route    => [/        => <>,                                  /
              /mcp     => mcp_mtron_http,                      /
              /docs    => target/docs,                         /
              /console => src/main/resources/web/console]      /
]@/sys/space/web/http
----


[discrete]
=== HTML Type

The type `html::T < rec::T` (a refinement of `rec::T`) represents an https://en.wikipedia.org/wiki/HTML[HTML] document.

[mtron]
----
html::T                                                    [-- <1> --]
*<http://phaseshift.studio/splash.html>                    [-- <2> --]
*<http://phaseshift.studio/splash.html/html/head/title>    [-- <3> --]
*<http://phaseshift.studio/splash.html>.as(str::T)         [-- <4> --]
----
<1> The structural definition of `html::T`.
<2> Retrieve the `index.html` of the website. Content-type yields `text/html` which for metatron maps to `html::T`.
<3> The `title` element of the `index.html` of the website.
<4> The `index.html` of the website as a `str::T` (`string => rec => string`).


[discrete]
=== Accessing REST APIs

When a https://en.wikipedia.org/wiki/REST[REST] endpoint has a URL address that matches an `httpspace` pattern, the REST resources can be used in metatron. This is possible because `httpspace` transforms data "in the wild" (e.g. `application/json`) into an isomorphic `obj`. If the newly mapped `obj` is typed, then it inherits the instructions for that type as defined by the `instset` of the type. As such, REST resources can be enriched/typed to become active computational objs in metatron.

A https://lmstudio.ai/[LMStudio] service will serve to demonstrate how to leverage foreign resources in metatron. LMStudio exposes an https://www.openapis.org/[OpenAPI]-compliant endpoint at `http://localhost:1234/v1` (this is specific to the author's local deployment of LMStudio).

[mtron]
----
*<http://localhost:1234/v1>            [-- <1> --]            
*<http://localhost:1234/v1/models>     [-- <2> --]
----
<1> An error server side, but demonstrates that the endpoint is alive.
<2> The `/models` resource contains a list of all LLM models available for use in LMStudio.

Once the desired REST resource has been accessed, it's possible to map the resource into a form that meets the structural requirements of an mtron `type`. In doing so, the resource then acquires the behaviors defined in the type's respective `instset`. For this example, that `instset` is `/m/llm`.

[mtron]
----
*/m/llm/model                   
*/m/llm/inst/+?dom=model
----
<1> The `model::T` type in `/m/llm`.
<2> The `/m/llm` instructions with a domain of `model::T`  (an object oriented perspective -- `obj.f()`).

When the REST resource is manipulated to fit the structural specification of `model::T`, then  `http://localhost:1234/v1/models` can be the source of `chat?#\<=model`.


[mtron]
----
*<http://localhost:1234/v1/models>.>>data/1.     /
  -<[provider=> !*/sys/space/lmstudio,           /
     name    => >>id.as(uri::T)].as(model::T)    /
  .chat('are you there?') 
----
<1> The OpenAPI `application/json` resource is morphed into a metatron `model::T` and then the model is chatted with.

[discrete]
=== WebSocket Space

The `wsspace::T` is similar to `httpspace::T`, but enables long running connections and bidirectional communication. A particular useful aspect of `wsspace::T` is for communication between two metatron instances. 

[discrete]
==== Remote Console

If another metatron instance is running on a remote machine, it's possible to route all console input to the remote metatron for evaluation. In order to make the experience seamless for the user, the `redirect/input` relation of `console::T` can be used.

NOTE: In the following example, the "remote" metatron instance is `localhost`. This is because all code examples in this documentation are evaluated when the documentation is compiled. Note that `localhost` can be set to any hostname or IP address that is running a metatron instance with a `wsspace::T` exposing the `mtron_ws::T` handler.

[mtron]
----
wsclient::[host=><ws://localhost:8555/mtron>]@/usr/ui/console/remote  [-- <1> --]
----
<1> creates a websocket connection to a remote metatron instance with a `wsspace::T` exposing an `mtron_ws::T` route.

In the local console UI (the REPL), use the `:redirect/input` metacommand to have all user input processed by an arbitrary `inst`. When that `inst` is a `wsclient::T.send_recv()`, then a remote console is effected.

[source,mtron]
----
mtron> :redirect/input inst?#{*}<=#{?}(to_send=>#{?}::T){*/usr/ui/console/remote.send_recv(*to_send)}
[INFO ] [/usr/ui/console] redirecting console input to inst?#{*}<=#{?}(to_send=>#{?}::T){*/usr/ui/console/remote.send_recv(*to_send)}
----

At this point, all console input is sent to the remote metatron instance, evaluated at that instance via the `mtron_ws::T` endpoint, where the results are returned to the local instance and displayed in the local console UI.

To have REPL input evaluated locally (the default behavior), set the `console::T.redirect/input` to `noobj`.

[source,mtron]
----
mtron> :redirect/input noobj
[INFO ] [/usr/ui/console] redirecting console input to noobj
mtron> :redirect/input
[INFO ] [/usr/ui/console] console input currently redirected to noobj
----

The `console::T.redirect/input` can be any `inst`. The flexibility of such redirection allows any number of use cases such as broadcasting, local processing w/ side effects, and more.