[discrete]
== Web Technologies

[%collapsible]
./m/web instset import and space constructions
====
[mtron]
----
[HIDDEN] import(/m/llm)
import(/m/web)
----
====

The `/m/web` instruction set enables a wide range of capabilities centered around `http`-based systems and websocket-based systems. Correspondingly, there exists `httpspace` and `wsspace` that manage respective network i/o connections. Along with these spaces are various serializers that provide the mtron encoding of common web document standards such as html, xml, json, markdown, and the like. 

[discrete]
=== HTTP Space

The `httpspace::T` is a space capable of spawning and managing `http` connection handlers both as servers and as clients. The pattern of an `httpspace` dictates the breadth of resources accessible. When `http://#` is the pattern, the world wide web becomes a source of metatron objs.

[mtron]
----
httpspace::[                                                   /
 host     => http://localhost:8777,                            /
 pattern  => http://#,                                         /
 route    => [/        => <>,                                  /
              /mcp     => mcp_mtron_http,                      /
              /docs    => target/docs,                         /
              /console => src/main/resources/web/console]      /
]@/sys/space/web/http
----


[discrete]
=== HTML Type

The type `html::T < rec::T` (a refinement of `rec::T`) represents an https://en.wikipedia.org/wiki/HTML[HTML] document.

[mtron]
----
html::T                                                    [-- <1> --]
*<http://phaseshift.studio/splash.html>                    [-- <2> --]
*<http://phaseshift.studio/splash.html/html/head/title>    [-- <3> --]
*<http://phaseshift.studio/splash.html>.as(str::T)         [-- <4> --]
----
<1> The structural definition of `html::T`.
<2> Retrieve the `index.html` of the website. Content-type yields `text/html` which for metatron maps to `html::T`.
<3> The `title` element of the `index.html` of the website.
<4> The `index.html` of the website as a `str::T` (`string => rec => string`).


[discrete]
=== Accessing REST APIs

When a https://en.wikipedia.org/wiki/REST[REST] endpoint has a URL address that matches an `httpspace` pattern, the REST resources can be used in metatron. This is possible because `httpspace` transforms data "in the wild" (e.g. `application/json`) into an isomorphic `obj`. If the newly mapped `obj` is typed, then it inherits the instructions for that type as defined by the `instset` of the type. As such, REST resources can be enriched/typed to become active computational objs in metatron.

A https://lmstudio.ai/[LMStudio] service will serve to demonstrate how to leverage foreign resources in metatron. LMStudio exposes an https://www.openapis.org/[OpenAPI]-compliant endpoint at `http://localhost:1234/v1` (this is specific to the author's local deployment of LMStudio).

[mtron]
----
*<http://localhost:1234/v1>                       
*<http://localhost:1234/v1/models>               
*<http://localhost:1234/v1/models/data/0/id>      
*<http://localhost:1234/v1/models/config-json/${  /
  *<http://localhost:1234/v1/models/data/0/id> }>   
----
<1> No result, but also no connection `fail::T`. The endpoint is alive.
<2> The `/models` resource contains a list of all LLM models available for use in LMStudio.
<3> Traversing the data within the resource is a function of extending the URI accordingly.
<4> Using URI template parameters to fetch more information about the model.

Once the desired REST resource has been accessed, it's possible to map the resource into a form that meets the structural requirements of an mtron `type`. In doing so, the resource then acquires the behaviors defined in the type's respective `instset`. For this example, that `instset` is `/m/llm`.

[mtron]
----
*/m/llm/model                   
*/m/llm/inst/+?dom=model
----
<1> The `model::T` type in `/m/llm`.
<2> The `/m/llm` instructions with a domain of `model::T`  (an object oriented perspective -- `obj.f()`).

When the REST resource is manipulated to fit the structural specification of `model::T`, then  `http://localhost:1234/v1/models/data/0` can be the source of `chat?#\<=model`.


[mtron]
----
*<http://localhost:1234/v1/models/data/0>>-.           /
  -<[name=>>>id.as(uri::T),                            /
     type=>>>object.as(uri::T),                        /
     provider=>|!*/sys/space/lmstudio].as(model::T)     /
  .chat('are you there?')                             
----
<1> The OpenAPI `application/json` resource is morphed into a metatron `model::T` and then the model is `chat`ted with.


