name: Continuous Integration using Java/Maven3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup OpenJDK 26
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'oracle'
          cache: maven
      - name: Install ijhttp
        run: |
          curl -f -s -L -o ijhttp.zip https://jb.gg/ijhttp/latest
          unzip -q ijhttp.zip -d ./tmp
          mkdir "${GITHUB_WORKSPACE}/target"
          mv ./tmp/*/* "${GITHUB_WORKSPACE}/target"
          rm ijhttp.zip
          ls -all target
          export PATH=$PATH:"${GITHUB_WORKSPACE}/target"
          echo "---- full path ----"
          target/ijhttp --version
          echo "---- relative path ----"
          ijhttp --version
      - name: Install with Maven
        run: mvn install --file pom.xml -Dtest='!httpSpaceTest, !fsSpaceTest'
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install websockets
      #- name: Build Documentation with Maven
      #  run: |
      #    bin/metatron "[log=>info,host=><ws://127.0.0.1:8999>,boot=><boot/boot.mtron>]" &
      #    mvn site --file pom.xml
      #- name: Update Dependency Graph
      #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
